//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesAppDatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Projection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projection()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        [Display(Name = " Date & Time ")]
        public System.DateTime dateTime { get; set; }
        [Display(Name = " Avilable Sits ")]
        public int AvailableSits { get; set; }
       
        public Nullable<int> hall_Id { get; set; }
        public int MovieId { get; set; }
    
        public virtual Hall Hall { get; set; }
        [Display(Name = " Movie ")]
        public virtual Movy Movy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
