//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesAppDatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public int raiting { get; set; }
        public string comment { get; set; }
        public System.DateTime dateTime { get; set; }
        public Nullable<int> client_Id { get; set; }
        public Nullable<int> Movie_Id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Movy Movy { get; set; }
    }
}
