//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesAppDatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public int numOfPeople { get; set; }
        public int ticketType { get; set; }
        public double price { get; set; }
        public Nullable<int> client_Id { get; set; }
        public Nullable<int> projection_Id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Projection Projection { get; set; }
    }
}
